// Generated by CoffeeScript 1.6.3
var app, express;

express = require('express');

app = express();

app.use(express["static"]('../'));

app.use(express.bodyParser());

port = 8889
console.log("using port " + port);
app.listen(port);

console.log('listening...');
